print ('привет')
x = input('введи число у которого хочешь узнать степени ')
x=int(x)
print(x)
print (x*x)
print (x*x*x)
print (x*x*x*x)
print (x*x*x*x*x)
print (x*x*x*x*x*x)
print (x*x*x*x*x*x*x)
